//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseReimbursment.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exp_Types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exp_Types()
        {
            this.Expense_Reports = new HashSet<Expense_Reports>();
        }
    
        public string ExpenseName { get; set; }
        public string ExpenseCode { get; set; }
        public string Approver_Rcode { get; set; }
    
        public virtual Emp_Roles Emp_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expense_Reports> Expense_Reports { get; set; }
    }
}
